#!/bin/bash

for i in "$@"
do
case $i in
    -v=*|--version=*)
    MYSQL_VERSION="${i#*=}"
    ;;
    -ep=*|--expose-port=*)
    MYSQL_PORT="${i#*=}"
    ;;
    -dv=*|--data-volume=*)
    MYSQL_DATA_VOLUME="${i#*=}"
    ;;
    -n=*|--name=*)
    MYSQL_CONTAINER_NAME="${i#*=}"
    ;;
    -rp=*|--root-password=*)
    MYSQL_ROOT_PASSWORD="${i#*=}"
    ;;
    -u=*|--user=*)
    MYSQL_USER="${i#*=}"
    ;;
    -p=*|--password=*)
    MYSQL_PASSWORD="${i#*=}"
    ;;
    -db=*|--database=*)
    MYSQL_DATABASE="${i#*=}"
    ;;
    --help)
    HELP=YES
    shift # past argument with no value 
    ;;
    --debug)
    DEBUG=YES
    shift # past argument with no value 
    ;;
    *)
        # unknown option
    ;;
esac
done

if [ "$DEBUG" == "YES" ]; then 
    set -x
fi

. ./defaults.properties

fDisplayUsage() {
    cat << EOF

 USAGE: ./run.sh 
     -rp | --root-password=<root password>  The password for the root user. Required
    [-v  | --version=<MySQL Version>   ]    MySQL version, defaults to 8.0
    [-ep | --expose-port=<MYSQL Port>  ]    Server expose port, defaults to 3336
    [-dv | --data-volume=<Data Volume> ]    The mapped data volume. Autogenerated if not supplied
    [-n  | --name=<Container Name> ]        The name of the docker container. Optional
    [--help]                                Displays this text
    [--debug]                               Runs the script in debug mode

EOF
}

fLog() {
   echo "[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] $*"
}

fPrintArgs() {
    MYSQL_VERSION=${MYSQL_VERSION:-$DEFAULT_MYSQL_VERSION}
    MYSQL_PORT=${MYSQL_PORT:-$DEFAULT_MYSQL_PORT}
    MYSQL_USER=${MYSQL_USER:-$DEFAULT_MYSQL_USER}
    MYSQL_PASSWORD=${MYSQL_PASSWORD:-$DEFAULT_MYSQL_PASSWORD}
    MYSQL_DATABASE=${MYSQL_DATABASE:-$DEFAULT_MYSQL_DATABASE}
    MYSQL_DATA_VOLUME=${MYSQL_DATA_VOLUME:-mysql_ext_${MYSQL_VERSION}_${MYSQL_CONTAINER_NAME:-'default'}_data}

    echo
    fLog " Preparing Docker container with the following properties: "
    fLog "     ** Version   = $MYSQL_VERSION"
    fLog "     ** Container = $MYSQL_CONTAINER_NAME"
    fLog "     ** User      = $MYSQL_USER"
    fLog "     ** Pass      = $MYSQL_PASSWORD"
    fLog "     ** Database  = $MYSQL_DATABASE"
    fLog "     ** Root Pass = $MYSQL_ROOT_PASSWORD"
    fLog "     ** Port      = $MYSQL_PORT"
    fLog "     ** Volume    = $MYSQL_DATA_VOLUME"
    echo
}

fValidateArgs() {
    if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
        echo " ERROR (-1): Root password is not specified!"
        fDisplayUsage
        exit -1
    fi
}

fBuildImageIfNeeded() {
    MYSQL_IMAGE="$DEFAULT_IMAGE_TAG:$MYSQL_VERSION"
    if [[ "$(docker images -q $MYSQL_IMAGE 2> /dev/null)" == "" ]]; then
        fLog " Creating image $MYSQL_IMAGE ..."
        ./build.sh -v=$MYSQL_VERSION 
    else
        fLog " Image $MYSQL_IMAGE is cached."
    fi
}

fCreateDataVolumeOrDie() {
    fLog " Creating volume $MYSQL_DATA_VOLUME ..."
    docker volume inspect $MYSQL_DATA_VOLUME 1> /dev/null 2> /dev/null
    if [ $? == 0 ]; then
        echo " ERROR (-4): Data volume $MYSQL_DATA_VOLUME already exists!"
        fDisplayUsage
        exit -4
    else
        docker volume create $MYSQL_DATA_VOLUME 1> /dev/null
    fi
}

fRunNamedContainerOrDie() {
    fLog " Creating cnamed ontainer $MYSQL_CONTAINER_NAME ..."
    docker container inspect $MYSQL_CONTAINER_NAME 1> /dev/null 2> /dev/null
    if [ $? == 0 ]; then
        echo " ERROR (-3): Container $MYSQL_CONTAINER_NAME already exists!"
        fDisplayUsage
        exit -3
    fi

    docker run \
        --name $MYSQL_CONTAINER_NAME \
        -p "$MYSQL_PORT:$DEFAULT_MYSQL_PORT" \
        -e "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" \
        -e "MYSQL_USER=$MYSQL_USER" \
        -e "MYSQL_PASSWORD=$MYSQL_PASSWORD" \
        -e "MYSQL_DATABASE=$MYSQL_DATABASE" \
        -v "$MYSQL_DATA_VOLUME:/var/lib/mysql" \
        -d "$MYSQL_IMAGE"
}

fRunContainer() {
    fLog " Creating container ..."
    docker run \
        -p "$MYSQL_PORT:$DEFAULT_MYSQL_PORT" \
        -e "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" \
        -e "MYSQL_USER=$MYSQL_USER" \
        -e "MYSQL_PASSWORD=$MYSQL_PASSWORD" \
        -e "MYSQL_DATABASE=$MYSQL_DATABASE" \
        -v "$MYSQL_DATA_VOLUME:/var/lib/mysql" \
        -d "$MYSQL_IMAGE"
}

if [ "$HELP" == "YES" ]; then 
    fDisplayUsage
else
    fPrintArgs
    fValidateArgs
    fBuildImageIfNeeded
    fCreateDataVolumeOrDie

    if [ -z "$MYSQL_CONTAINER_NAME" ]; then
        fRunContainer
    else
        fRunNamedContainerOrDie
    fi

    fLog " Done!"
    echo
fi